<?php 
$title = "View Report - " . htmlspecialchars($report['title']);
include '../app/views/shared/header.php'; 
include '../app/views/shared/navbar.php';
include '../app/views/shared/layout-header.php'; 
?>

<div class="main-content">
    <div class="container-fluid px-4">
        <!-- Report Header -->
        <div class="d-flex justify-content-between align-items-center mb-4">
            <div>
                <h1 class="h3 mb-0 text-gray-800">
                    <i class="fas fa-file-alt text-primary me-2"></i>
                    <?= htmlspecialchars($report['title']) ?>
                </h1>
                <p class="mb-0 text-muted">
                    Generated on <?= date('F j, Y g:i A', strtotime($report['created_at'])) ?>
                </p>
            </div>
            <div>
                <a href="/admin/reports" class="btn btn-secondary">
                    <i class="fas fa-arrow-left me-1"></i> Back to Reports
                </a>
                <button class="btn btn-success" onclick="window.print()">
                    <i class="fas fa-print me-1"></i> Print
                </button>
            </div>
        </div>

        <!-- Report Info Card -->
        <div class="card shadow mb-4">
            <div class="card-header bg-gradient-primary text-white">
                <h6 class="mb-0"><i class="fas fa-info-circle me-2"></i>Report Information</h6>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <strong>Report Type:</strong><br>
                        <span class="badge bg-<?= 
                            $report['type'] === 'books' ? 'primary' : 
                            ($report['type'] === 'students' ? 'info' : 
                            ($report['type'] === 'borrows' ? 'success' : 
                            ($report['type'] === 'overdue' ? 'warning' : 'secondary')))
                        ?> mt-1">
                            <?= ucfirst($report['type']) ?>
                        </span>
                    </div>
                    <div class="col-md-3">
                        <strong>Library:</strong><br>
                        <?= htmlspecialchars($library['name'] ?? 'All Libraries') ?>
                    </div>
                    <div class="col-md-3">
                        <strong>Generated By:</strong><br>
                        <?= htmlspecialchars($generated_by['username'] ?? 'System') ?>
                    </div>
                    <div class="col-md-3">
                        <strong>Date Range:</strong><br>
                        <?php if ($report['date_range_start'] && $report['date_range_end']): ?>
                            <?= date('M j, Y', strtotime($report['date_range_start'])) ?> - 
                            <?= date('M j, Y', strtotime($report['date_range_end'])) ?>
                        <?php else: ?>
                            All Time
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>

        <!-- Report Content -->
        <div class="card shadow">
            <div class="card-header bg-gradient-primary text-white">
                <h6 class="mb-0"><i class="fas fa-chart-bar me-2"></i>Report Data</h6>
            </div>
            <div class="card-body">
                <?php if (!empty($report['data'])): ?>
                    <?php 
                    // Decode JSON data if stored as JSON
                    $reportData = is_string($report['data']) ? json_decode($report['data'], true) : $report['data'];
                    ?>
                    
                    <?php if (is_array($reportData) && !empty($reportData)): ?>
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <thead class="table-light">
                                    <tr>
                                        <?php foreach (array_keys($reportData[0]) as $header): ?>
                                            <th><?= ucwords(str_replace('_', ' ', $header)) ?></th>
                                        <?php endforeach; ?>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($reportData as $row): ?>
                                        <tr>
                                            <?php foreach ($row as $value): ?>
                                                <td><?= htmlspecialchars($value ?? 'N/A') ?></td>
                                            <?php endforeach; ?>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        
                        <div class="mt-3">
                            <p class="text-muted mb-0">
                                <i class="fas fa-list me-1"></i>
                                Total Records: <strong><?= count($reportData) ?></strong>
                            </p>
                        </div>
                    <?php else: ?>
                        <div class="alert alert-info">
                            <i class="fas fa-info-circle me-2"></i>
                            This report contains summary information only.
                        </div>
                    <?php endif; ?>
                <?php else: ?>
                    <div class="alert alert-warning">
                        <i class="fas fa-exclamation-triangle me-2"></i>
                        No data available for this report.
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<style>
.bg-gradient-primary {
    background: linear-gradient(135deg, #7c3aed 0%, #6366f1 100%);
}

@media print {
    .btn, .navbar, .sidebar, .card-header, .main-content {
        display: none !important;
    }
    
    .card {
        border: none !important;
        box-shadow: none !important;
    }
    
    .table {
        font-size: 0.9rem;
    }
}
</style>

<?php 
include '../app/views/shared/layout-footer.php';
include '../app/views/shared/footer.php'; 
?>
